_target_: src.models.EBMLatentTilting
_recursive_: false  

lambda_reg: 1e-1

base_model: "/Users/hhjs/Documents/Projects/HackathonMlLS1506/HackathonEBM/prop_binary_mnist_vae-2025-09-19T10-13-41/checkpoints/last.ckpt"

energy_net:
  _target_: src.layers.MLP
  input_dim: 64
  hidden_dims: [64, 64]
  output_dim: 1
  spectral_norm: True
  activation: "swish"

sampler:
  _target_: src.samplers.SGLD
  input_dim: 64
  input_shape: []
  sample_size: ${train.batch_size}
  steps: 60
  step_size: 0.2
  noise_std: 0.005
