image_samples: 
  _target_: src.callbacks.ImageSamples
  num_samples: 64
  steps: 256
  return_init: True
  every_n_epochs: 10

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "epoch"