# Trains a MIWAE model with MCAR missingness on MNIST (50 % missing)


defaults:
  - train: default
  - model: vae/mnist
  - data: mnist
  - callbacks: image_vae

# Change model target to MIWAE
model:
  _target_: src.models.MIWAE

data:
  dataset:
    missing_rate: 0.5
    threshold: 0    # 0 to apply to all pixels

