
defaults:
  - train: default
  - model: vae/binary_mnist
  - data: prop_binary_mnist
  - callbacks: image_vae_prop_debiasing


data:
  dataset:
    dataset_fraction: 0.9
    proportions: {
            0: 0.12,
            1: 0.33,
            2: 0.28,
            3: 0.20,
            4: 0.07,
            5: 0.0,
            6: 0.0,
            7: 0.0,
            8: 0.0,
            9: 0.0,
        }
    

