_target_: src.models.EBMTilting
_recursive_: false  

wgan_gp_lambda: 0.0
l2_energy_lambda: 0.0
l2_params_lambda: 0.0


base_model: "/Users/hhjs/Documents/Projects/HackathonMlLS1506/HackathonEBM/prop_binary_mnist_vae-2025-09-19T10-13-41/checkpoints/last.ckpt"

energy_net:
  _target_: src.layers.ConvEncoder
  input_channels: ${data.dim}
  input_shape: ${data.shape}
  latent_dim: 1
  hidden_channels: [32, 64, 128, 128]
  kernel_sizes: [5, 3, 3, 3]
  strides: [2, 2, 2, 2]
  paddings: [4, 1, 1, 1]
  batch_norm: False
  activation: "swish"
  probabilistic: False

sampler:
  _target_: src.samplers.SGLD
  input_dim: ${data.dim}
  input_shape: ${data.shape}  
  sample_size: ${train.batch_size}
  steps: 60
  step_size: 0.2
  noise_std: 0.005
