_target_: src.models.VAE
_recursive_: false  

K: 5
latent_dim: 64

likelihood:
  _target_: src.likelihoods.GaussianLikelihood
  min_logvar: -2.3
  learn_var: False

encoder:
  _target_: src.layers.ConvEncoder
  input_channels: ${data.dim}
  input_shape: ${data.shape}
  latent_dim: ${model.latent_dim}
  hidden_channels: [64, 64, 128]
  kernel_sizes: [4, 4, 4]
  strides: [2, 2, 1]
  paddings: [1, 1, 0]
  batch_norm: True
    
decoder:
  _target_: src.layers.ConvDecoder
  latent_dim: ${model.latent_dim}
  output_channels: ${data.dim}
  output_shape: ${data.shape}
  hidden_channels: ${reverse:${model.encoder.hidden_channels}}
  kernel_sizes: ${reverse:${model.encoder.kernel_sizes}}
  strides: ${reverse:${model.encoder.strides}}
  paddings: ${reverse:${model.encoder.paddings}}
  batch_norm: True

